AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Cluster with ASG and Capacity Provider integration'

Parameters:
  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - dev
      - qa
      - stage
      - prod

  ClusterName:
    Type: String
    Description: Name of the ECS Cluster

  EnableContainerInsights:
    Type: String
    Description: Enable CloudWatch Container Insights
    AllowedValues:
      - enabled
      - disabled
    Default: enabled

  InstanceType:
    Type: String
    Description: EC2 instance type for the cluster
    Default: t4g.medium

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for the ASG

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for the ASG

  MinSize:
    Type: Number
    Description: Minimum number of instances in the ASG
    Default: 0

  MaxSize:
    Type: Number
    Description: Maximum number of instances in the ASG  
    Default: 1

  DesiredCapacity:
    Type: Number  
    Description: Desired number of instances in the ASG
    Default: 1

  RootVolumeSize:
    Type: Number
    Description: Size of the root EBS volume in GB
    Default: 30

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName
      ClusterSettings:
        - Name: containerInsights
          Value: !Ref EnableContainerInsights
      Tags:
        - Key: Name
          Value: !Ref ClusterName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # IAM Role for EC2 instances to talk to ECS
  ECSInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role

  ECSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref ECSInstanceRole]

  # Launch Template defining the EC2 configuration
  ECSLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub '${ClusterName}-LT'
      LaunchTemplateData:
        ImageId: !Sub '{{resolve:ssm:/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id}}'
        InstanceType: !Ref InstanceType
        IamInstanceProfile:
          Name: !Ref ECSInstanceProfile
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: !Ref RootVolumeSize
              VolumeType: gp3
              Encrypted: true
              DeleteOnTermination: true
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            # Create the ecs.config file with the ECS cluster name
            sudo bash -c 'cat <<EOT >> /etc/ecs/ecs.config
            ECS_CLUSTER=${ClusterName}
            ECS_REGION=us-east-1
            ECS_ENABLE_TASK_IAM_ROLE=true
            ECS_ENABLE_SPOT_INSTANCE_DRAINING=true
            EOT'
        MetadataOptions:
          HttpEndpoint: enabled
          HttpTokens: required

  # Auto Scaling Group
  ECSAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn:
      - ECSCluster
      - EC2Role
    Properties:
      VPCZoneIdentifier: !Ref SubnetIds
      LaunchTemplate:
        LaunchTemplateId: !Ref ECSLaunchTemplate
        Version: !GetAtt ECSLaunchTemplate.LatestVersionNumber
      MinSize: !Ref: MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      NewInstancesProtectedFromScaleIn: true
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: "true"

  # Capacity Provider
  ECSCapacityProvider:
    Type: AWS::ECS::CapacityProvider
    Properties:
      Name: !Sub '${ClusterName}-CapacityProvider'
      AutoScalingGroupProvider:
        AutoScalingGroupArn: !Ref ECSAutoScalingGroup
        ManagedScaling:
          Status: ENABLED
          TargetCapacity: 100
        ManagedTerminationProtection: ENABLED

  # Link Capacity Provider to Cluster
  ClusterCapacityProviderAssociation:
    Type: AWS::ECS::ClusterCapacityProviderAssociations
    Properties:
      Cluster: !Ref ECSCluster
      CapacityProviders:
        - !Ref ECSCapacityProvider
      DefaultCapacityProviderStrategy:
        - CapacityProvider: !Ref ECSCapacityProvider
          Weight: 1
          Base: 1

Outputs:
  ClusterName:
    Description: Name of the ECS Cluster
    Value: !Ref ECSCluster
    Export:
      Name: !Sub '${AWS::StackName}-ClusterName'

  ClusterArn:
    Description: ARN of the ECS Cluster
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ClusterArn'