AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Service with ALB integration'

Parameters:
  Environment:
    Type: String
    Description: Environment name
  
  ApplicationName:
    Type: String
    Description: Name of the application
  
  ClusterName:
    Type: String
    Description: Name of the ECS Cluster
  
  TaskDefinitionArn:
    Type: String
    Description: ARN of the Task Definition
  
  DesiredCount:
    Type: Number
    Description: Desired number of tasks
    Default: 1
  
  MinCapacity:
    Type: Number
    Description: Minimum number of tasks
    Default: 1
  
  MaxCapacity:
    Type: Number
    Description: Maximum number of tasks
    Default: 1
  
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs for ECS tasks
  
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group ID for ECS tasks
  
  TargetGroupArn:
    Type: String
    Description: ARN of the Target Group
  
  ContainerName:
    Type: String
    Description: Name of the container in task definition
  
  ContainerPort:
    Type: Number
    Description: Port on which the container listens
    Default: 80
  
  HealthCheckGracePeriodSeconds:
    Type: Number
    Description: Grace period for health checks
    Default: 60
  
  DeploymentMaximumPercent:
    Type: Number
    Description: Maximum percent of tasks during deployment
    Default: 200
  
  DeploymentMinimumHealthyPercent:
    Type: Number
    Description: Minimum healthy percent during deployment
    Default: 100
  
  EnableECSManagedTags:
    Type: String
    Description: Enable ECS managed tags
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
  
  PropagateTags:
    Type: String
    Description: Propagate tags from task definition or service
    AllowedValues:
      - TASK_DEFINITION
      - SERVICE
      - NONE
    Default: SERVICE

Resources:
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${Environment}-${ApplicationName}-service'
      Cluster: !Ref ClusterName
      TaskDefinition: !Ref TaskDefinitionArn
      DesiredCount: !Ref DesiredCount
      LaunchType: EC2
      PlatformVersion: LATEST
      HealthCheckGracePeriodSeconds: !Ref HealthCheckGracePeriodSeconds
      DeploymentConfiguration:
        MaximumPercent: !Ref DeploymentMaximumPercent
        MinimumHealthyPercent: !Ref DeploymentMinimumHealthyPercent
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups:
            - !Ref SecurityGroupId
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroupArn
      EnableECSManagedTags: !Ref EnableECSManagedTags
      PropagateTags: !Ref PropagateTags
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-${ApplicationName}-service'
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  ServiceName:
    Description: Name of the ECS Service
    Value: !GetAtt ECSService.Name
    Export:
      Name: !Sub '${AWS::StackName}-ServiceName'
  
  ServiceArn:
    Description: ARN of the ECS Service
    Value: !Ref ECSService
    Export:
      Name: !Sub '${AWS::StackName}-ServiceArn'